### ISSUE TITLE
Is this still active

### ISSUE THREAD

**Issue by RajaSrinivasan** [Lucretia/meta-ada#3]
Are you still active? I am interested in getting ada up and running with rocko. My target is ARM. thanks, srini

**Comment by Lucretia** [comment]
Afraid not. Last I tried it failed miserably as they'd heavily modified the sources to work differently.

You'd be better off forking Yocto and adding in Ada directly, inlcuding in a bootstrap for the target, which you can grab the url for from sarnold's ada-overlay.
